apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogpost-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogpost-client
  template:
    metadata:
      labels:
        app: blogpost-client
    spec:
      containers:
        - name: blogpost-client
          image: arun6783/blogpost-client
          env:
            - name: PORT
              value: '3000'
            - name: POSTS_SRV_HOST
              value: 'blogpost-posts-srvce'
            - name: COMMENTS_SRV_HOST
              value: 'blogpost-comments-srv'
            - name: QUERY_SRV_HOST
              value: 'blogpost-query-srv'
---
kind: Service
apiVersion: v1
metadata:
  name: blogpost-client-srv
spec:
  selector:
    app: blogpost-client
  ports:
    - name: blogpost-client-tcp
      port: 3000
      targetPort: 3000
  type: LoadBalancer
