apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogpost-eventbus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogpost-eventbus
  template:
    metadata:
      labels:
        app: blogpost-eventbus
    spec:
      containers:
        - name: blogpost-eventbus
          image: arun6783/blogpost-eventbus
          env:
            - name: POSTS_SRV_HOST
              value: 'blogpost-posts-srvce'
            - name: COMMENTS_SRV_HOST
              value: 'blogpost-comments-srv'
            - name: QUERY_SRV_HOST
              value: 'blogpost-query-srv'
            - name: MODERATION_SRV_HOST
              value: 'blogpost-moderation-srv'
---
kind: Service
apiVersion: v1
metadata:
  name: blogpost-eventbus-srv
spec:
  selector:
    app: blogpost-eventbus
  ports:
    - name: blogpost-eventbus-tcp
      port: 4005
      targetPort: 4005
  type: LoadBalancer
